# Generated by Django 6.1.1 on 2026-10-05 14:39

import cmnsd.models.mixins.TokenMixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=cmnsd.models.mixins.TokenMixin.generate_public_id, editable=False, help_text='Short unique ID for public URL / API use', max_length=20, unique=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True)),
                ('day', models.SmallIntegerField(blank=True, null=True)),
                ('date_qualifier', models.CharField(choices=[('exact', 'exact'), ('circa', 'circa'), ('before', 'before'), ('after', 'after')], default='exact', help_text='How sure the date is', max_length=10)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('kind', models.CharField(choices=[('birth', 'birth'), ('death', 'death'), ('marriage', 'marriage'), ('migration', 'migration'), ('historical', 'historical'), ('other', 'other')], max_length=20)),
                ('kind_freetext', models.CharField(blank=True, help_text="Custom label for this event - required when kind is 'other'", max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('people', models.ManyToManyField(blank=True, related_name='events', to='people.person')),
                ('places', models.ManyToManyField(blank=True, related_name='events', to='places.place')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
                'indexes': [models.Index(fields=['kind', 'year'], name='events_even_kind_e64ae8_idx')],
            },
        ),
    ]
