# Generated by Django 6.1.1 on 2026-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('birth', 'birth'), ('death', 'death'), ('marriage', 'marriage'), ('divorce', 'divorce'), ('migration', 'migration'), ('historical', 'historical'), ('other', 'other')], max_length=20),
        ),
    ]
