# Generated by Django 6.1.1 on 2026-10-05 14:39

import cmnsd.models.mixins.TokenMixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=cmnsd.models.mixins.TokenMixin.generate_public_id, editable=False, help_text='Short unique ID for public URL / API use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='c', max_length=1)),
                ('visibility', models.CharField(choices=[('p', 'Public'), ('c', 'Community'), ('f', 'Family'), ('q', 'Private')], default='c', max_length=1)),
                ('name', models.CharField(blank=True, help_text='Define a name for this comment., optional', max_length=255, null=True, verbose_name='Name')),
                ('content', models.TextField(help_text='Define the content of this comment., required', verbose_name='Content')),
                ('target_id', models.PositiveIntegerField()),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('nl', 'Dutch')], help_text='Leave blank to fall back to browser/site default language detection', max_length=10)),
                ('ui_state', models.JSONField(blank=True, default=dict)),
                ('family', models.ManyToManyField(blank=True, help_text="Users to treat as family for 'family'-visibility content", related_name='family_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferences',
                'verbose_name_plural': 'Preferences',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=cmnsd.models.mixins.TokenMixin.generate_public_id, editable=False, help_text='Short unique ID for public URL / API use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='c', max_length=1)),
                ('visibility', models.CharField(choices=[('p', 'Public'), ('c', 'Community'), ('f', 'Family'), ('q', 'Private')], default='c', max_length=1)),
                ('translation_alias', models.TextField(blank=True, default='', help_text='Comma-separated translations, auto-populated on save')),
                ('slug', models.CharField(help_text='Identifier in URL (automatically generated)', max_length=64)),
                ('name', models.CharField(help_text='Name of tag', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Description of this tag, why it is relevant')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.tag')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['parent__name', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='core_tag_unique_name_per_parent', nulls_distinct=False), models.UniqueConstraint(fields=('parent', 'slug'), name='core_tag_unique_slug_per_parent', nulls_distinct=False)],
            },
        ),
    ]
