# Generated by Django 6.1.1 on 2026-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='superstitious',
            field=models.BooleanField(default=False, help_text="Show star signs on people's pages"),
        ),
    ]
