# Generated by Django 6.1.1 on 2026-10-05 14:39

import cmnsd.models.mixins.TokenMixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
        ('events', '0001_initial'),
        ('people', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=cmnsd.models.mixins.TokenMixin.generate_public_id, editable=False, help_text='Short unique ID for public URL / API use', max_length=20, unique=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True)),
                ('day', models.SmallIntegerField(blank=True, null=True)),
                ('date_qualifier', models.CharField(choices=[('exact', 'exact'), ('circa', 'circa'), ('before', 'before'), ('after', 'after')], default='exact', help_text='How sure the date is', max_length=10)),
                ('kind', models.CharField(choices=[('scratch', 'scratch'), ('todo', 'to do'), ('question', 'question'), ('hypothesis', 'hypothesis'), ('conclusion', 'conclusion'), ('context', 'context')], default='scratch', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True, help_text='The reasoning, a quoted source, the anecdote - Markdown')),
                ('confidence', models.CharField(blank=True, choices=[('certain', 'certain'), ('probable', 'probable'), ('uncertain', 'uncertain')], max_length=20)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='c', max_length=1)),
                ('visibility', models.CharField(choices=[('p', 'Public'), ('c', 'Community'), ('f', 'Family'), ('q', 'Private')], default='q', max_length=1)),
                ('content', models.ManyToManyField(blank=True, related_name='notes', to='content.content')),
                ('events', models.ManyToManyField(blank=True, related_name='notes', to='events.event')),
                ('people', models.ManyToManyField(blank=True, related_name='notes', to='people.person')),
                ('places', models.ManyToManyField(blank=True, related_name='notes', to='places.place')),
                ('related_notes', models.ManyToManyField(blank=True, related_name='linked_from', to='notes.note')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='core.tag')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-date_modified'],
            },
        ),
    ]
