# Generated by Django 4.0.1 on 2022-01-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_tmpdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpdoc',
            name='source',
            field=models.ImageField(upload_to='tmp'),
        ),
    ]
