# Generated by Django 4.0.1 on 2022-01-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('archive', '0005_alter_tmpdoc_source'),
    ]

    operations = [
        migrations.RenameModel('Document', 'Image'
        ),
    ]

