# Generated by Django 4.0.1 on 2022-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_alter_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(upload_to=''),
        ),
    ]
