# Generated by Django 4.0.1 on 2022-01-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_alter_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_portrait_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portrait', to='archive.person'),
        ),
    ]
