# Generated by Django 4.0.1 on 2022-01-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='Dit veld is alleen zichtbaar voor jou en voor de site-beheerder(s). Vul je e-mailadres in zodat we je een wachtwoord-reset email kunnen sturen als je niet langer kan inloggen.', max_length=254),
        ),
    ]
