# Generated by Django 4.0.1 on 2022-01-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_alter_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='middle_name',
            new_name='given_names',
        ),
    ]
