# Generated by Django 4.0.1 on 2022-01-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_rename_middle_name_person_given_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyrelations',
            name='type',
            field=models.CharField(default='parent', max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, help_text='Roepnaam', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_names',
            field=models.CharField(blank=True, help_text='Voornamen', max_length=255),
        ),
    ]
