# Generated by Django 4.0.1 on 2022-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_familyrelations_type_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Roepnaam'),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_names',
            field=models.CharField(blank=True, max_length=255, verbose_name='Voornamen'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Achternaam'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bijnaam'),
        ),
    ]
