# Generated by Django 4.0.1 on 2022-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_alter_person_first_name_alter_person_given_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyrelations',
            name='type',
            field=models.CharField(choices=[('parent', 'Parent'), ('partner', 'Partner')], default='parent', max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_names',
            field=models.CharField(blank=True, help_text='Alle voornamen, inclusief roepnaam', max_length=255, verbose_name='Voornamen'),
        ),
    ]
