# Generated by Django 4.0.1 on 2022-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='in_goup',
            field=models.ManyToManyField(blank=True, help_text='Group images', related_name='images', to='archive.Group'),
        ),
    ]
