# Generated by Django 4.0.1 on 2022-02-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_image_in_goup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='in_goup',
            new_name='in_group',
        ),
    ]
