# Generated by Django 4.0.1 on 2022-02-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_rename_in_goup_image_in_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='desciption',
            new_name='description',
        ),
    ]
