# Generated by Django 4.0.1 on 2022-02-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_rename_desciption_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='images',
        ),
    ]
