# Generated by Django 4.0.1 on 2022-02-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_remove_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='images', to='archive.Attachment'),
        ),
    ]
