# Generated by Django 4.0.2 on 2022-02-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_image_attachments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TmpDoc',
        ),
    ]
