# Generated by Django 4.1 on 2022-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_delete_tmpdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='married_name',
            field=models.CharField(blank=True, help_text='Achternaam van echtgeno(o)t(e)', max_length=255, verbose_name='Getrouwde Achternaam'),
        ),
        migrations.AddField(
            model_name='person',
            name='moment_of_death_unconfirmed',
            field=models.BooleanField(default=False, help_text='Set True if moment of death is unknown but person has deceased.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, help_text='Achternaam bij geboorte', max_length=255, verbose_name='Achternaam'),
        ),
    ]
