# Generated by Django 4.1 on 2022-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0027_person_married_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='orientation',
            field=models.CharField(choices=[('p', 'portrait'), ('l', 'landscape'), ('s', 'square'), ('u', 'unknown')], default='u', max_length=1),
        ),
    ]
