# Generated by Django 4.1 on 2022-12-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0028_image_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='attachment',
        ),
    ]
