# Generated by Django 4.1 on 2022-12-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0030_image_height_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
