# Generated by Django 4.1 on 2022-12-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0032_remove_image_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='day_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='day_of_death',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='month_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='month_of_death',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
