# Generated by Django 4.1 on 2022-12-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0033_person_day_of_birth_person_day_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
