# Generated by Django 4.1 on 2022-12-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0037_person_other_user_alter_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='other_user',
        ),
    ]
