# Generated by Django 4.1 on 2022-12-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0039_comment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='month_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'januari'), (2, 'februari'), (3, 'maart'), (4, 'april'), (5, 'mei'), (6, 'juni'), (7, 'juli'), (8, 'augustus'), (9, 'september'), (10, 'oktober'), (11, 'november'), (12, 'december')], null=True),
        ),
    ]
