# Generated by Django 4.1 on 2022-12-11 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0041_alter_person_month_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='day_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
