# Generated by Django 4.1 on 2022-12-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0042_alter_person_day_of_birth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familyrelations',
            unique_together={('up', 'down', 'type')},
        ),
    ]
