# Generated by Django 4.1 on 2022-12-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0044_person_date_created_person_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
