# Generated by Django 4.1 on 2022-12-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0051_tag_date_created_tag_date_modified_tag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='upload_is_hidden',
            new_name='show_new_uploads',
        ),
    ]
