# Generated by Django 4.1 on 2022-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0053_alter_preference_show_new_uploads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='notes', to='archive.attachment'),
        ),
        migrations.AddField(
            model_name='note',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='notes', to='archive.image'),
        ),
    ]
