# Generated by Django 4.1 on 2022-12-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0055_attachment_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='desciption',
            new_name='description',
        ),
    ]
