# Generated by Django 4.1 on 2022-12-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0057_attachment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
