# Generated by Django 4.1.4 on 2022-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0058_alter_attachment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='Possible to attach file to an image. Use for pdf, doc, excel, etc.', null=True, upload_to='files'),
        ),
    ]
