# Generated by Django 4.1.4 on 2022-12-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0059_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
