# Generated by Django 4.1.4 on 2022-12-28 10:03

import archive.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0060_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.CharField(default=archive.models.image.random_string, max_length=255, unique=True),
        ),
    ]
