# Generated by Django 4.1.4 on 2023-01-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0061_alter_image_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title', max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('scope', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('show_in_index', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('people', models.ManyToManyField(blank=True, help_text='People referenced in family tree', related_name='trees', to='archive.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
