# Generated by Django 4.1.4 on 2023-01-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0062_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='show_in_index',
        ),
    ]
