# Generated by Django 4.1.4 on 2023-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0063_remove_tree_show_in_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
