# Generated by Django 4.1.4 on 2023-01-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0064_person_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
