# Generated by Django 4.1.4 on 2023-01-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0065_delete_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='private',
            field=models.BooleanField(default=False, help_text='Private Mode limits the information being shared'),
        ),
    ]
