# Generated by Django 4.1.4 on 2023-01-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0066_person_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='orientation',
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
    ]
