# Generated by Django 4.1.4 on 2023-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0067_remove_image_orientation_alter_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
