# Generated by Django 4.2.4 on 2023-12-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0068_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.FileField(upload_to=''),
        ),
    ]
