# Generated by Django 4.2.4 on 2023-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0069_alter_image_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_names', 'last_name'), 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='given_names',
            new_name='first_names',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('x', 'not stored')], default='x', max_length=1),
        ),
    ]
