# Generated by Django 4.2.4 on 2023-12-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0070_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='show_in_index',
            new_name='visibility_frontpage',
        ),
        migrations.AddField(
            model_name='image',
            name='visibility_person_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(blank=True, help_text='Indien afwijkend van eerste voornaam', max_length=255, verbose_name='Roepnaam'),
        ),
    ]
