# Generated by Django 4.2.10 on 2024-02-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0073_preference_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='loved_by', to='archive.image'),
        ),
    ]
