# Generated by Django 5.2.7 on 2025-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0081_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='bootstrap icon name, e.g. "camera" for category icons', max_length=32),
        ),
    ]
