# Generated by Django 5.2.7 on 2025-11-14 11:19

from django.db import migrations

def set_category_icons(apps, schema_editor):
    Category = apps.get_model('archive', 'Category')

    icons = {
        'Photo': 'camera',
        'Portrait': 'person-badge',
        'Document': 'file-text',
        'News-article': 'newspaper',
        'Advertisement': 'megaphone',
        'Artwork': 'brush',
        'Uncategorized': 'question-circle',
    }

    for name, icon in icons.items():
        try:
            obj = Category.objects.get(name=name)
            obj.icon = icon
            obj.save()
        except Category.DoesNotExist:
            pass  # silently ignore
        
class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0082_category_icon'),
    ]

    operations = [
        migrations.RunPython(set_category_icons)
    ]
