# Generated by Django 5.2.7 on 2025-11-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0083_auto_20251114_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='portrait_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='portrait_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='portrait_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='portrait_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
