# Generated by Django 5.2.7 on 2025-11-18 14:04

import cmnsd.models.cmnsd_basemodel
from django.db import migrations, models
import uuid

def populate_tokens(apps, schema_editor):
    Comment = apps.get_model('archive', 'Comment')
    for obj in Comment.objects.all():
        # Generate a unique token per row (use your generate_public_id() if preferred)
        obj.token = uuid.uuid4().hex[:20]
        obj.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0084_person_portrait_h_person_portrait_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1),
        ),
        # 1. Add nullable, non-unique field
        migrations.AddField(
            model_name='comment',
            name='token',
            field=models.CharField(max_length=20, null=True, blank=True, editable=False),
        ),

        # 2. Populate tokens row-by-row
        migrations.RunPython(populate_tokens),

        # 3. Now enforce uniqueness + remove null if wanted
        migrations.AlterField(
            model_name='comment',
            name='token',
            field=models.CharField(
                max_length=20,
                unique=True,
                blank=True,
                editable=False,
            ),
        ),
    ]