# Generated by Django 5.2.8 on 2025-11-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0086_remove_comment_is_deleted_alter_comment_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
