# Generated by Django 5.2.8 on 2025-11-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0089_tag_parent_alter_tag_name_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this tag, why it is relevant'),
        ),
    ]
