# Generated by Django 5.2.8 on 2025-11-22 19:05

import cmnsd.models.cmnsd_basemodel
import django.utils.timezone
from django.db import migrations, models
import uuid 

def populate_tokens(apps, schema_editor):
    Mod = apps.get_model('archive', 'Group')
    for obj in Mod.objects.all():
        # Generate a unique token per row (use your generate_public_id() if preferred)
        obj.token = uuid.uuid4().hex[:20]
        obj.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0091_note_status_note_token_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='group',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        # 2. Populate tokens row-by-row
        migrations.RunPython(populate_tokens),
        # 3. Now enforce uniqueness + remove null if wanted
        migrations.AlterField(
            model_name='group',
            name='token',
            field=models.CharField(
                max_length=20,
                unique=True,
                blank=True,
                editable=False,
            ),
        ),
    ]
