# Generated by Django 5.2.8 on 2025-11-24 09:07

import cmnsd.models.cmnsd_basemodel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0093_attachment_date_created_attachment_date_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_at',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
    ]
