# Generated by Django 5.2.8 on 2025-11-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0094_rename_uploaded_at_image_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_at',
        ),
    ]
