# Generated by Django 5.2.8 on 2025-11-29 10:55
import cmnsd.models.cmnsd_basemodel
import django.utils.timezone
from django.db import migrations, models
import uuid 

def populate_tokens(apps, schema_editor):
    Mod = apps.get_model('archive', 'Image')
    for obj in Mod.objects.all():
        # Generate a unique token per row (use your generate_public_id() if preferred)
        obj.token = uuid.uuid4().hex[:20]
        obj.save(update_fields=['token'])

def set_status(apps, schema_editor):
    Attachment = apps.get_model("archive", "Image")
    Attachment.objects.filter(is_deleted=True).update(status="x")


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0096_alter_attachment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='image',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True),
        ),
        # 2. Populate tokens row-by-row
        migrations.RunPython(populate_tokens),
        migrations.RunPython(set_status),
        # 3. Now enforce uniqueness + remove null if wanted
        migrations.AlterField(
            model_name='image',
            name='token',
            field=models.CharField(
                max_length=20,
                unique=True,
                blank=True,
                editable=False,
            ),
        ),
        # --- 4. Remove the legacy field ---
        migrations.RemoveField(
            model_name='image',
            name='is_deleted',
        ),
    ]
