# Generated by Django 5.2.8 on 2025-11-29 13:39

import cmnsd.models.cmnsd_basemodel
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid

def populate_tokens(apps, schema_editor):
    Mod = apps.get_model('archive', 'Person')
    for obj in Mod.objects.all():
        # Generate a unique token per row (use your generate_public_id() if preferred)
        obj.token = uuid.uuid4().hex[:20]
        obj.save(update_fields=['token'])

class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0097_image_status_image_token_alter_image_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        # 2. Populate tokens row-by-row
        migrations.RunPython(populate_tokens),

        # 3. Now enforce uniqueness + remove null if wanted
        migrations.AlterField(
            model_name='person',
            name='token',
            field=models.CharField(
                max_length=20,
                unique=True,
                blank=True,
                editable=False,
            ),
        ),
        
    ]
