# Generated by Django 5.2.8 on 2025-11-30 13:06

import cmnsd.models.cmnsd_basemodel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0098_remove_image_family_person_status_person_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='bootstrap icon name', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
    ]
