# Generated by Django 5.2.8 on 2025-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0100_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='alternative_to', to='archive.location'),
        ),
    ]
