# Generated by Django 5.2.8 on 2025-11-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0101_location_alternatives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
