# Generated by Django 5.2.8 on 2025-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0102_alter_location_options_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
