# Generated by Django 5.2.8 on 2025-11-30 18:32

import cmnsd.models.cmnsd_basemodel
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0103_alter_location_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, help_text='bootstrap icon name', max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeLineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], help_text='select a month', null=True)),
                ('day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('images', models.ManyToManyField(blank=True, related_name='events', to='archive.image')),
                ('locations', models.ManyToManyField(blank=True, related_name='events', to='archive.location')),
                ('notes', models.ManyToManyField(blank=True, related_name='events', to='archive.note')),
                ('people', models.ManyToManyField(blank=True, related_name='events', to='archive.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='archive.tag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.eventtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'month', 'day', 'name'],
            },
        ),
    ]
