# Generated by Django 5.2.8 on 2025-11-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0104_eventtype_timelineevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['year', 'month', 'day']},
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='slug',
        ),
    ]
