# Generated by Django 5.2.8 on 2025-11-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0105_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the event', max_length=255),
        ),
    ]
