# Generated by Django 5.2.8 on 2025-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0106_timelineevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='major',
            field=models.BooleanField(default=False),
        ),
    ]
