# Generated by Django 5.2.8 on 2025-12-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0107_eventtype_major_timelineevent_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='major',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='major',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='importance',
            field=models.IntegerField(choices=[(0, 'event'), (1, 'life-event'), (2, 'milestone')], default=0, help_text='Define the importance of this event type. Higher values indicate greater importance.'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='importance',
            field=models.IntegerField(choices=[(0, 'event'), (1, 'life-event'), (2, 'milestone')], default=0, help_text='Define the importance of this event. Higher values indicate greater importance.'),
        ),
    ]
