# Generated by Django 5.2.8 on 2025-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0108_remove_eventtype_major_remove_timelineevent_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='type',
            field=models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('marriage', 'Marriage'), ('other', 'Other'), ('general', 'General')], default='other', max_length=20),
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='importance',
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='select a month', null=True),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
