# Generated by Django 5.2.8 on 2025-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0110_event_delete_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='events', to='archive.image', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='events', to='archive.location', verbose_name='locations'),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='events', to='archive.person', verbose_name='people'),
        ),
    ]
