# Generated by Django 5.2.8 on 2025-12-06 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0111_event_images_event_locations_event_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
    ]
