# Generated by Django 5.2.8 on 2025-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0112_alter_event_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('parent', 'name')},
        ),
    ]
