# Generated by Django 5.2.8 on 2025-12-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0113_alter_location_name_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
