# Generated by Django 5.2.8 on 2025-12-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0114_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('parent', 'name')},
        ),
    ]
