# Generated by Django 5.2.8 on 2025-12-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0115_alter_location_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='portrait_of',
            field=models.ManyToManyField(blank=True, help_text='Tag people for whom this image is a portrait', related_name='portraits', to='archive.person'),
        ),
    ]
