# Generated by Django 5.2.8 on 2025-12-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0116_image_portrait_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['parent__parent__name', 'parent__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='person',
            name='day_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='day_of_death',
        ),
        migrations.RemoveField(
            model_name='person',
            name='month_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='month_of_death',
        ),
        migrations.RemoveField(
            model_name='person',
            name='year_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='year_of_death',
        ),
    ]
