# Generated by Django 5.2.8 on 2025-12-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0117_alter_location_options_remove_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='familyrelations',
            index=models.Index(fields=['up', 'type'], name='archive_fam_up_id_b05e15_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelations',
            index=models.Index(fields=['down', 'type'], name='archive_fam_down_id_e3fba8_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelations',
            index=models.Index(fields=['up', 'down', 'type'], name='archive_fam_up_id_9bff12_idx'),
        ),
    ]
