# Generated by Django 5.2.8 on 2025-12-20 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0118_familyrelations_archive_fam_up_id_b05e15_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='archive_eve_type_3552f0_idx'),
        ),
    ]
