# Generated by Django 5.2.8 on 2025-12-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0119_event_archive_eve_type_3552f0_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='place_of_death',
        ),
    ]
