# Generated by Django 5.2.8 on 2025-12-28 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0120_remove_person_place_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='archive_eve_type_3552f0_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type', 'year'], name='archive_eve_type_905ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_names'], name='archive_per_last_na_72b666_idx'),
        ),
    ]
