# Generated by Django 6.0.3 on 2026-04-05 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0121_remove_event_archive_eve_type_3552f0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_portrait_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portrait', to='archive.person'),
        ),
    ]
