# Generated by Django 6.0.3 on 2026-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0123_book_collection_collectionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='scan',
        ),
        migrations.AddField(
            model_name='book',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='books', to='archive.attachment'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='books/covers/'),
        ),
    ]
