# Generated by Django 6.0.3 on 2026-09-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0124_remove_collectionitem_scan_book_attachments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='persons',
            new_name='people',
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'book'), name='unique_collection_book'),
        ),
    ]
