# Generated by Django 6.1.1 on 2026-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0125_rename_persons_collection_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='read_on',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
