# Generated by Django 6.1.1 on 2026-10-05 14:39

import cmnsd.models.mixins.TokenMixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=cmnsd.models.mixins.TokenMixin.generate_public_id, editable=False, help_text='Short unique ID for public URL / API use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='c', max_length=1)),
                ('visibility', models.CharField(choices=[('p', 'Public'), ('c', 'Community'), ('f', 'Family'), ('q', 'Private')], default='c', max_length=1)),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier, generated from the name', max_length=255, unique=True)),
                ('given_name', models.CharField(blank=True, help_text='All official first name(s) of the person', max_length=255)),
                ('called_name', models.CharField(blank=True, help_text='The name the person is commonly called by, if different from the given name', max_length=255)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the person at birth', max_length=255)),
                ('married_name', models.CharField(blank=True, help_text='Married name of the person, if any', max_length=255)),
                ('nickname', models.CharField(blank=True, help_text='Nickname of the person, if any', max_length=255)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other'), ('x', 'unknown')], default='x', max_length=1)),
                ('family_connection', models.CharField(choices=[('family', 'family'), ('possibly_family', 'possibly family'), ('outsider', 'outsider')], default='family', help_text='How this person relates to the family', max_length=20)),
                ('biography', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False, help_text='If checked, this person still appears in the family tree but has no clickable detail page - for people who are part of the tree (e.g. living relatives) but not represented with viewable details')),
                ('related_user', models.OneToOneField(blank=True, help_text='The user account associated with this person, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorizing or labeling this person', related_name='people', to='core.tag')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'given_name', 'married_name', 'called_name', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='PersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('parent', 'parent'), ('partner', 'partner'), ('other', 'other')], max_length=10)),
                ('person_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='people.person')),
                ('person_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='people.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'given_name'], name='people_pers_last_na_7cb132_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['slug'], name='people_pers_slug_152379_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['person_from', 'relation_type'], name='people_pers_person__315391_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['person_to', 'relation_type'], name='people_pers_person__5cbdff_idx'),
        ),
        migrations.AddConstraint(
            model_name='personrelation',
            constraint=models.CheckConstraint(condition=models.Q(('person_from', models.F('person_to')), _negated=True), name='personrelation_no_self_relation'),
        ),
        migrations.AlterUniqueTogether(
            name='personrelation',
            unique_together={('person_from', 'person_to', 'relation_type')},
        ),
    ]
