"""
Django settings for fmly project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import environ
from pathlib import Path
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read environment variables from .env file
env = environ.Env(
  DEBUG=(bool, False),
  ENVIRONMENT=(str, 'production'),
)
environ.Env.read_env(BASE_DIR / '.env')


# Security
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'content',
    'people',
    'events',
    'places',
    'notes',
    'dashboard',
    'core',
    'legacy_import',
    'cmnsd',
    'sorl.thumbnail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'cmnsd.middleware.user_language.UserLanguageMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cmnsd.middleware.html_output.HtmlOutputMiddleware',
]

ROOT_URLCONF = 'fmly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
              'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cmnsd.context_processors.setting_data.setting_data',
                'cmnsd.context_processors.edit_mode.edit_mode',
                'core.context_processors.site_settings.site_settings',
              ],
              'builtins': [
                'django.templatetags.i18n',
                'django.templatetags.static',
              ],
        },
    },
]

WSGI_APPLICATION = 'fmly.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
  'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'CET'
USE_I18N = True
USE_TZ = True

LANGUAGES = (
  ('en', _('English')),
  ('nl', _('Dutch')),
)
LOCALE_PATHS = [BASE_DIR / 'locale/']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Static / media files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'public' / 'static'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Static files with their content hash in their name (cmnsd/storage.py):
# collectstatic is required for every deploy, and a changed file - a
# cmnsd.js module - always reaches the browser. Tests use plain names (no
# collected manifest there).
import sys
TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'
STORAGES = {
  'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
  'staticfiles': {'BACKEND': (
    'django.contrib.staticfiles.storage.StaticFilesStorage' if TESTING
    else 'cmnsd.storage.ManifestStaticFilesStorage'
  )},
}

MEDIA_URL = 'content/'
# private/, never served directly: content/<year>/ for uploads (see
# content/files.py), cache/ for sorl thumbnails - both only via sendfile.
MEDIA_ROOT = BASE_DIR / 'private'
SENDFILE_ROOT = MEDIA_ROOT
SENDFILE_URL = '/protected/'   # nginx: location /protected/ { internal; alias …/private/; }
SENDFILE_BACKEND = env('SENDFILE_BACKEND', default='django_sendfile.backends.simple')  # nginx in production

# SORL Thumbnail
# Decodes large JPEG scans at reduced size for thumbnails - see
# content/thumbnail_engine.py (and content/apps.py for the pixel limit).
THUMBNAIL_ENGINE = 'content.thumbnail_engine.Engine'
THUMBNAIL_DEBUG = env('DEBUG', default=False)  # True while developing, if you want verbose errors instead of silent fallback

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@localhost')
REGISTRATION_NOTIFY_EMAIL = env('REGISTRATION_NOTIFY_EMAIL', default=None)
# New accounts may comment (core prepare_release makes the group).
REGISTER_DEFAULT_GROUPS = env.list('REGISTER_DEFAULT_GROUPS', default=['Visitors'])

# App Config: CMNSD
SITE_NAME = env('SITE_NAME', default='A Family Archive')
META_DESCRIPTION = env('META_DESCRIPTION', default='An archive of a family\'s history, memories, and stories.')

# CMNSD Settings
# Default status for new objects created in the admin or via API. 'c' = concept, 
# 'p' = published
CMNSD_DEFAULT_MODEL_STATUS = 'c' 
# Storage location for the list of users that are allowed to view a given object when
# its visibility is set to "family".
CMNSD_VISIBILITY_FAMILY_LOOKUP_STORAGE = 'user__preferences__family'
# Markdown extensions to use for rendering Markdown content. 
# See https://python-markdown.github.io/extensions/ for a list of available extensions.
CMNSD_MARKDOWN_EXTENSIONS = [
  'fenced_code', 'nl2br', 'tables',
  'cmnsd.markdown.autolink:AutolinkExtension', 'cmnsd.markdown.external_links:ExternalLinksExtension',
]
# When a user registers, the account requires approval before logging in.
# If false, the user can log in immediately after registration. 
CMNSD_REGISTRATION_REQUIRES_APPROVAL = env.bool('CMNSD_REGISTRATION_REQUIRES_APPROVAL', default=False)
# The string used to compound parent-child names, e.g. "Parent: Child". The child name 
# is appended to the parent name with this string in between. This is used for 
# auto-generating names of child objects when a name isn't provided.
CMNSD_PARENT_COMPOUNDER = ': '
# HTML tag used by the |highlight templatetag to wrap a matched substring.
# <mark> is HTML5's own element for "text highlighted for reference/search
# purposes" - browsers give it a default yellow background, overridable in CSS.
CMNSD_HIGHLIGHT_TAG = 'mark'
# HtmlOutputMiddleware: pretty-print HTML in DEBUG via BeautifulSoup's
# prettify(). Off by default - prettify() inserts a newline around every
# tag regardless of inline/block, which visibly corrupts text containing
# an inline tag mid-word (e.g. |highlight's <mark>). Turn on only for a
# template-structure debugging session, not as a standing dev setting.
CMNSD_DEBUG_PRETTIFY = env.bool('CMNSD_DEBUG_PRETTIFY', default=False)
# cmnsd.js deferred loading: placeholders marked data-load-on-ready are
# filled by the API after page load. Set to False to render those fields
# server-side in the page request instead - a kill switch for when
# cmnsd.js is broken. See cmnsd/documentation/javascript/loading.md.
CMNSD_LOAD_ON_READY = env.bool('CMNSD_LOAD_ON_READY', default=True)
# cmnsd.api has a search character to enable freetext search in all
# text fields. Set to None to disable freetext search entirely, or to a
# string to use as the search character. Default is "?" (e.g. ?searchterm).
CMNSD_SEARCH_CHARACTER = env('CMNSD_SEARCH_CHARACTER', default='q')

# Without this, LogoutView renders django.contrib.admin's own generic
# "Logged out | Django site admin" fallback page directly instead of
# redirecting - which also means MessageLogoutView's flashed "signed out"
# message never gets seen (it'd only show on the next page load, and
# without a redirect this render IS the response).
LOGOUT_REDIRECT_URL = '/'

# Logging
# Without this, a 500 with DEBUG=False is only mailed to ADMINS (none set) -
# it leaves no trace. Warnings and errors, with their traceback, go to
# stderr: supervisord writes them to the gunicorn log, runserver to the
# terminal. cmnsd logs sign-ins and failed sign-ins at INFO.
LOGGING = {
  'version': 1,
  'disable_existing_loggers': False,
  'handlers': {'console': {'class': 'logging.StreamHandler'}},
  'loggers': {
    'django': {'handlers': ['console'], 'level': 'WARNING'},
    'cmnsd': {'handlers': ['console'], 'level': 'INFO'},
  },
}

# Debug toolbar
# Only add the debug toolbar if DEBUG is True, 
# to avoid exposing sensitive information in production.
if DEBUG:
  INSTALLED_APPS += ['debug_toolbar']
  MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
  INTERNAL_IPS = ['127.0.0.1']
