# Generated by Django 6.1.1 on 2026-10-05 14:39

import cmnsd.models.mixins.TokenMixin
import content.files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, help_text='As written on the book; link the author as a person above', max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=cmnsd.models.mixins.TokenMixin.generate_public_id, editable=False, help_text='Short unique ID for public URL / API use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='c', max_length=1)),
                ('visibility', models.CharField(choices=[('p', 'Public'), ('c', 'Community'), ('f', 'Family'), ('q', 'Private')], default='c', max_length=1)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True)),
                ('day', models.SmallIntegerField(blank=True, null=True)),
                ('date_qualifier', models.CharField(choices=[('exact', 'exact'), ('circa', 'circa'), ('before', 'before'), ('after', 'after')], default='exact', help_text='How sure the date is', max_length=10)),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier, generated from the name', max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('unknown', 'unknown'), ('photo', 'photo'), ('document', 'document'), ('book', 'book'), ('object', 'object'), ('recording', 'recording')], default='unknown', max_length=20)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=content.files.content_upload_to)),
                ('original_filename', models.CharField(blank=True, help_text='The name the file arrived with', max_length=255)),
                ('checksum', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Where this came from: a person, archive or URL', max_length=1000)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('thumb_crop_x', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('thumb_crop_y', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('thumb_crop_w', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('thumb_crop_h', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('thumb_rotation', models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'content',
                'ordering': ['position', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(choices=[('civil_record', 'civil record'), ('identity', 'identity document'), ('service_record', 'service record'), ('war_record', 'war record'), ('newspaper', 'newspaper'), ('advertisement', 'advertisement'), ('publication_excerpt', 'publication excerpt'), ('personal', 'personal paper'), ('research', 'research'), ('other', 'other')], default='other', max_length=30)),
                ('language', models.CharField(blank=True, choices=[('nl', 'Dutch'), ('en', 'English'), ('id', 'Indonesian'), ('ms', 'Malay'), ('jv', 'Javanese'), ('de', 'German'), ('fr', 'French'), ('pt', 'Portuguese'), ('la', 'Latin'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('other', 'other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_kind', models.CharField(choices=[('portrait', 'portrait'), ('group', 'group'), ('candid', 'candid'), ('historical', 'historical'), ('other', 'other')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_x', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('crop_y', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('crop_w', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('crop_h', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_primary', models.BooleanField(default=False)),
                ('rotation', models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('original', 'original'), ('translation', 'translation')], default='original', max_length=20)),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('id', 'Indonesian'), ('ms', 'Malay'), ('jv', 'Javanese'), ('de', 'German'), ('fr', 'French'), ('pt', 'Portuguese'), ('la', 'Latin'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('other', 'other')], max_length=10)),
                ('method', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic, not checked'), ('automatic_checked', 'automatic, checked')], default='manual', max_length=20)),
                ('text', models.TextField()),
                ('incomplete', models.BooleanField(default=False, help_text='Only part of the text is transcribed so far')),
            ],
            options={
                'ordering': ['kind', 'language'],
            },
        ),
    ]
