# Generated by Django 6.1.1 on 2026-10-05 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
        ('events', '0001_initial'),
        ('people', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored_books', to='people.person'),
        ),
        migrations.AddField(
            model_name='content',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='content', to='events.event'),
        ),
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='content.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='content', to='people.person'),
        ),
        migrations.AddField(
            model_name='content',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='content', to='places.place'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='content', to='core.tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcontent',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_detail', to='content.content'),
        ),
        migrations.AddField(
            model_name='documentcontent',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_detail', to='content.content'),
        ),
        migrations.AddField(
            model_name='photocontent',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_detail', to='content.content'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_links', to='content.content'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_links', to='people.person'),
        ),
        migrations.AddField(
            model_name='content',
            name='portrait_of',
            field=models.ManyToManyField(blank=True, related_name='portraits', through='content.Portrait', to='people.person'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='content.content'),
        ),
        migrations.AddConstraint(
            model_name='portrait',
            constraint=models.UniqueConstraint(fields=('person', 'content'), name='content_portrait_unique_person_content'),
        ),
        migrations.AddConstraint(
            model_name='portrait',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='content_portrait_one_primary_per_person'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(fields=('content', 'language'), name='content_transcript_one_per_language', violation_error_message='This item already has a transcript in that language.'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'original')), fields=('content',), name='content_transcript_one_original', violation_error_message='This item already has an original - add this as a translation.'),
        ),
    ]
