# Generated by Django 6.1.1 on 2026-10-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_book_year_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontent',
            name='publication_year',
        ),
    ]
