# Generated by Django 6.1.1 on 2026-10-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_bookcontent_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontent',
            name='author',
        ),
    ]
