# Generated by Django 4.1.4 on 2023-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0003_attendeeoptions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeoptions',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
