# Generated by Django 4.1.4 on 2023-02-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0004_attendeeoptions_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='datepicker.event'),
        ),
    ]
