# Generated by Django 4.1.4 on 2023-02-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0005_alter_option_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeoptions',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='datepicker.attendee'),
        ),
        migrations.AlterField(
            model_name='attendeeoptions',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendees', to='datepicker.option'),
        ),
    ]
