# Generated by Django 4.1.4 on 2023-02-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0006_alter_attendeeoptions_attendee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendeeoptions',
            old_name='choice',
            new_name='status',
        ),
    ]
