# Generated by Django 4.1.4 on 2023-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0007_rename_choice_attendeeoptions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeoptions',
            name='status',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('M', 'maybe'), ('U', 'unknown')], default='U', max_length=1),
        ),
    ]
