# Generated by Django 4.1.4 on 2023-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0008_alter_attendeeoptions_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-event_start']},
        ),
    ]
