# Generated by Django 4.1.4 on 2023-02-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0009_alter_option_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['event_start']},
        ),
    ]
